package view;

import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import daoImpl.AlunoImpl;
import daoImpl.PalestraImpl;
import daoImpl.RelatorioImpl;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.bean.Aluno;
import model.bean.Palestra;
import model.bean.Relatorio;

/**
 *
 * @author Dhyego Pedroso
 */
public class JanelaAlunos extends javax.swing.JInternalFrame {

    static int openFrameCount = 0;
    static final int xOffset = 30, yOffset = 30;

    public JanelaAlunos() throws SQLException {

        super("Document #" + (++openFrameCount),
                true,
                true);
        try {
            setSize(400, 220);
            setLocation(xOffset * openFrameCount, yOffset * openFrameCount);
            initComponents();
            atualizarTabela();
            desativarComponentes();

            PalestraImpl palestraImpl = new PalestraImpl();
            for (Palestra p : palestraImpl.pesquisarAll()) {
                BoxPalestra.addItem(p);
            }

            DefaultTableModel modeloAuto = (DefaultTableModel) TabelaAlunos.getModel();
            TabelaAlunos.setRowSorter(new TableRowSorter(modeloAuto));
        } catch (Exception e) {
        }

    }

    public void desativarComponentes() {
        BtnValidar.setEnabled(false);
    }

    public void ativarComponentes() {
        BtnValidar.setEnabled(true);
    }

    public void atualizarTabela() {
        try {
            DefaultTableModel modeloAuto = (DefaultTableModel) TabelaAlunos.getModel();
            modeloAuto.setNumRows(0);
            AlunoImpl impl = new AlunoImpl();
            for (Aluno a : impl.pesquisarAll()) {
                modeloAuto.addRow(new Object[]{
                    a.getId(),
                    a.getNome(),
                    a.getNomeCurso(),
                    a.getFaseCurso()});
            }
        } catch (SQLException ex) {
            Logger.getLogger(JanelaAlunos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void pesquisarNome(String nome) {
        try {
            DefaultTableModel modeloAuto = (DefaultTableModel) TabelaAlunos.getModel();
            modeloAuto.setNumRows(0);
            AlunoImpl impl = new AlunoImpl();
            for (Aluno a : impl.pesquisarPorNome(nome)) {
                modeloAuto.addRow(new Object[]{
                    a.getId(),
                    a.getNome(),
                    a.getNomeCurso(),
                    a.getFaseCurso()});
            }
        } catch (SQLException ex) {
            Logger.getLogger(JanelaAlunos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void limparCampos() {
        TxtNomeAluno.setText("");
        TxtNomeCurso.setText("");
        TxtFaseCurso.setText("");
        TxtPesquisarAluno.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaAlunos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtNomeAluno = new javax.swing.JTextField();
        TxtNomeCurso = new javax.swing.JTextField();
        TxtFaseCurso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BtnValidar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        TxtPesquisarAluno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnNovoAluno = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BoxPalestra = new javax.swing.JComboBox<>();

        setClosable(true);
        setMaximizable(true);
        setTitle("ALUNOS");

        TabelaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Curso", "Fase"
            }
        ));
        TabelaAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaAlunosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaAlunos);
        if (TabelaAlunos.getColumnModel().getColumnCount() > 0) {
            TabelaAlunos.getColumnModel().getColumn(0).setMinWidth(30);
            TabelaAlunos.getColumnModel().getColumn(0).setMaxWidth(50);
            TabelaAlunos.getColumnModel().getColumn(1).setMinWidth(350);
            TabelaAlunos.getColumnModel().getColumn(1).setMaxWidth(450);
            TabelaAlunos.getColumnModel().getColumn(2).setMinWidth(250);
            TabelaAlunos.getColumnModel().getColumn(2).setMaxWidth(400);
            TabelaAlunos.getColumnModel().getColumn(3).setMinWidth(100);
            TabelaAlunos.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Aluno"));

        jLabel1.setText("Nome:");

        jLabel2.setText("Curso:");

        TxtNomeAluno.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TxtNomeAluno.setEnabled(false);

        TxtNomeCurso.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TxtNomeCurso.setEnabled(false);

        TxtFaseCurso.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TxtFaseCurso.setEnabled(false);

        jLabel5.setText("fase");

        BtnValidar.setText("Validar Presença");
        BtnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnValidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtNomeCurso)))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(TxtFaseCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnValidar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFaseCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(BtnValidar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar"));

        TxtPesquisarAluno.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TxtPesquisarAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPesquisarAlunoKeyPressed(evt);
            }
        });

        jLabel4.setText("Aluno:");

        btnNovoAluno.setText("Novo Aluno");
        btnNovoAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoAlunoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtPesquisarAluno)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(btnNovoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 168, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtPesquisarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNovoAluno)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Palestra do Dia"));

        jLabel3.setText("Palestra:");

        BoxPalestra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma palestra" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BoxPalestra, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoxPalestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtPesquisarAlunoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPesquisarAlunoKeyPressed
        pesquisarNome(TxtPesquisarAluno.getText());
    }//GEN-LAST:event_TxtPesquisarAlunoKeyPressed

    private void TabelaAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaAlunosMouseClicked
        if (TabelaAlunos.getSelectedRow() != -1) {
            String valor = this.TabelaAlunos.getValueAt(TabelaAlunos.getSelectedRow(), 0).toString();
            int id = Integer.parseInt(valor);
            AlunoImpl alunoImpl = new AlunoImpl();
            try {
                List<Aluno> alunos = (List<Aluno>) alunoImpl.pesquisarPorId(id);
                for (Aluno aluno : alunos) {
                    TxtNomeAluno.setText(aluno.getNome());
                    TxtNomeCurso.setText(aluno.getNomeCurso());
                    TxtFaseCurso.setText(String.valueOf(aluno.getFaseCurso() + "º"));
                    ativarComponentes();
                }
            } catch (SQLException ex) {
                Logger.getLogger(JanelaAlunos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_TabelaAlunosMouseClicked

    private void BtnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnValidarActionPerformed

        if (BoxPalestra.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma palestra!!");
        } else {
            try {
                if (TabelaAlunos.getSelectedRow() != -1) {
                    String valor = this.TabelaAlunos.getValueAt(TabelaAlunos.getSelectedRow(), 0).toString();
                    int id = Integer.parseInt(valor);

                    Aluno aluno = new Aluno();
                    aluno.setId(id);

                    Palestra palestra = (Palestra) BoxPalestra.getSelectedItem();
                    palestra.setId(palestra.getId());

                    Relatorio relatorio = new Relatorio();
                    RelatorioImpl relatorioImpl = new RelatorioImpl();
                    relatorio.setAluno(aluno);
                    relatorio.setPalestra(palestra);
                    relatorioImpl.salvar(relatorio);

                    limparCampos();
                    desativarComponentes();
                }
            } catch (SQLException ex) {
                Logger.getLogger(JanelaAlunos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_BtnValidarActionPerformed

    private void btnNovoAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoAlunoMouseClicked
        CadastroAluno cadastroAluno = new CadastroAluno(null, closable);
    }//GEN-LAST:event_btnNovoAlunoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> BoxPalestra;
    private javax.swing.JButton BtnValidar;
    private javax.swing.JTable TabelaAlunos;
    private javax.swing.JTextField TxtFaseCurso;
    private javax.swing.JTextField TxtNomeAluno;
    private javax.swing.JTextField TxtNomeCurso;
    private javax.swing.JTextField TxtPesquisarAluno;
    private javax.swing.JButton btnNovoAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
