/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import daoImpl.RelatorioImpl;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Relatorio;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;

/**
 *
 * @author dhyeg
 */
public class JanelaRelatorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form JanelaRelatorio
     */
    public JanelaRelatorio() {
        try {
            initComponents();
            atualizarTabela();
            this.setMaximizable(true);
        } catch (Exception e) {
        }
    }

    public void atualizarTabela() {
        try {
            DefaultTableModel modeloAuto = (DefaultTableModel) TabelaRelatorio.getModel();
            modeloAuto.setNumRows(0);
            RelatorioImpl impl = new RelatorioImpl();
            for (Relatorio r : impl.pesquisarAll()) {
                SimpleDateFormat dataHora = new SimpleDateFormat("dd/MM/yyyy     HH:mm:ss");
                modeloAuto.addRow(new Object[]{
                    r.getId(),
                    r.getAluno().getNome(),
                    r.getAluno().getNomeCurso(),
                    r.getAluno().getFaseCurso(),
                    r.getPalestra().getTitulo(),
                    r.getPalestra().getDia(),
                    dataHora.format(r.getData())});
            }
        } catch (SQLException ex) {
            Logger.getLogger(JanelaRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void expExcel() {
        Integer rows = TabelaRelatorio.getModel().getRowCount();
        if (rows > 0) {
            JFileChooser seleccionar = new JFileChooser();
            File arquivo;
            if (seleccionar.showDialog(null, "Exportar Excel") == JFileChooser.APPROVE_OPTION) {
                arquivo = seleccionar.getSelectedFile();
                int cantFila = TabelaRelatorio.getRowCount();
                int cantColumna = TabelaRelatorio.getColumnCount();
                Workbook wb;
                wb = new HSSFWorkbook();
                Sheet folha = wb.createSheet("  ");

                try {
                    for (int i = -1; i < cantFila; i++) {
                        Row fila = folha.createRow(i + 1);
                        for (int j = 0; j < cantColumna; j++) {
                            Cell celda = fila.createCell(j);
                            if (i == -1) {
                                celda.setCellValue(String.valueOf(TabelaRelatorio.getColumnName(j)));
                            } else {
                                celda.setCellValue(String.valueOf(TabelaRelatorio.getValueAt(i, j)));
                            }
                            wb.write(new FileOutputStream(arquivo + ".xls"));
                        }
                    }
                    JOptionPane.showMessageDialog(null, "Planilha exportada com sucesso.");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Por favor tente novamente" + e);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaRelatorio = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnGerarRelatorio = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        TabelaRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome Aluno", "Curso", "Fase", "Palestra", "Dia da Palestra", "Hora Presença"
            }
        ));
        jScrollPane1.setViewportView(TabelaRelatorio);
        if (TabelaRelatorio.getColumnModel().getColumnCount() > 0) {
            TabelaRelatorio.getColumnModel().getColumn(0).setMinWidth(25);
            TabelaRelatorio.getColumnModel().getColumn(0).setMaxWidth(30);
            TabelaRelatorio.getColumnModel().getColumn(1).setMinWidth(250);
            TabelaRelatorio.getColumnModel().getColumn(1).setMaxWidth(300);
            TabelaRelatorio.getColumnModel().getColumn(2).setMinWidth(150);
            TabelaRelatorio.getColumnModel().getColumn(2).setMaxWidth(200);
            TabelaRelatorio.getColumnModel().getColumn(3).setMinWidth(70);
            TabelaRelatorio.getColumnModel().getColumn(3).setMaxWidth(100);
            TabelaRelatorio.getColumnModel().getColumn(4).setMinWidth(150);
            TabelaRelatorio.getColumnModel().getColumn(4).setMaxWidth(200);
            TabelaRelatorio.getColumnModel().getColumn(5).setMinWidth(80);
            TabelaRelatorio.getColumnModel().getColumn(5).setMaxWidth(100);
            TabelaRelatorio.getColumnModel().getColumn(6).setMinWidth(150);
            TabelaRelatorio.getColumnModel().getColumn(6).setMaxWidth(200);
        }

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGerarRelatorio.setText("Gerar relatorio");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGerarRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGerarRelatorio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
        expExcel();

    }//GEN-LAST:event_btnGerarRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaRelatorio;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
