package view;

import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author felipedania
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public JanelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        JanelaValidarAluno = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        novoAluno = new javax.swing.JMenuItem();
        MenuPalestra = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        MenuGerarRelatorio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1105, 750));

        PainelPrincipal.setPreferredSize(new java.awt.Dimension(1300, 852));

        javax.swing.GroupLayout PainelPrincipalLayout = new javax.swing.GroupLayout(PainelPrincipal);
        PainelPrincipal.setLayout(PainelPrincipalLayout);
        PainelPrincipalLayout.setHorizontalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1770, Short.MAX_VALUE)
        );
        PainelPrincipalLayout.setVerticalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );

        jMenu3.setText("Validar Presença");

        JanelaValidarAluno.setText("Validar Aluno");
        JanelaValidarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JanelaValidarAlunoActionPerformed(evt);
            }
        });
        jMenu3.add(JanelaValidarAluno);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Novo Aluno");

        novoAluno.setText("Novo Aluno");
        novoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(novoAluno);

        jMenuBar1.add(jMenu1);

        MenuPalestra.setText("Nova Palestra");

        jMenuItem1.setText("Cadastra Palestra");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuPalestra.add(jMenuItem1);

        jMenuBar1.add(MenuPalestra);

        menuRelatorio.setText("Gerar Relatorio");

        MenuGerarRelatorio.setText("Gerar Relatorio");
        MenuGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGerarRelatorioActionPerformed(evt);
            }
        });
        menuRelatorio.add(MenuGerarRelatorio);

        jMenuBar1.add(menuRelatorio);

        jMenu2.setText("Sair");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1770, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void JanelaValidarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JanelaValidarAlunoActionPerformed
        JanelaAlunos janelaAlunos;
        try {
            janelaAlunos = new JanelaAlunos();
            janelaAlunos.setVisible(true);

            PainelPrincipal.add(janelaAlunos);
            janelaAlunos.setSelected(true);
            janelaAlunos.setMaximizable(true);
            janelaAlunos.setMaximum(true);
        } catch (SQLException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_JanelaValidarAlunoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        JanelaNovaPalestra janelaNovaPalestra = new JanelaNovaPalestra();
        PainelPrincipal.add(janelaNovaPalestra);
        janelaNovaPalestra.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MenuGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGerarRelatorioActionPerformed
        JanelaRelatorio janelaRelatorio = new JanelaRelatorio();
        PainelPrincipal.add(janelaRelatorio);
        janelaRelatorio.setVisible(true);
    }//GEN-LAST:event_MenuGerarRelatorioActionPerformed

    private void novoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoAlunoActionPerformed
       CadastroAluno cadastroAluno = new CadastroAluno(this, rootPaneCheckingEnabled);
    }//GEN-LAST:event_novoAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JanelaValidarAluno;
    private javax.swing.JMenuItem MenuGerarRelatorio;
    private javax.swing.JMenu MenuPalestra;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenuItem novoAluno;
    // End of variables declaration//GEN-END:variables
}
